# -*- coding: utf-8 -*-
"""with_train_audi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bRcA61Pnym63WoE83ERoh8yyT_DGbhcY
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df = pd.read_csv('Audi_A1_listings.csv')
df.head()

df.drop(columns = ['index', 'href', 'PPY', 'MileageRank', 'PriceRank', 'PPYRank', 'Score'], inplace = True)

df.head(3)

df.columns =['yil', 'kasa','mil', 'motor', 'ps', 'vites', 'yakit', 'sahip', 'fiyat']

df.head(3)
df.info()

df['motor'] = df['motor'].str.replace('L', ' ').astype(float)

df.head(3)

df = pd.get_dummies(df, ['kasa', 'vites', 'yakit'], drop_first=True, dtype=int)

df.head(3)

X = df.drop('fiyat', axis = 1)
y = df['fiyat']

X_train,X_test,y_train,y_test = train_test_split(X,y, train_size = 0.75, random_state = 22)

lm = LinearRegression()
model = lm.fit(X_train, y_train)
model.score(X_test, y_test)

model.predict([[2018,30000,1.4,100,5,0,1]])

